### ISSUE TITLE
Magnet errors can't be assigned

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#35]
Hi, Thomas
When I add some errors to dipoles, cpymad can't calculate the right "x" values, while in the madx it works well. If cpymad can't recognize the errors anyway I think.
```python
import matplotlib.pylab as plt
from cpymad.madx import Madx
madx = Madx(command_log="HIMM_log.madx")
madx.command.call(file="HIMM_cpymad")
twiss0 = madx.twiss(sequence='himm')
plt.plot(twiss0['s'], twiss0['x'], label='x')
```
cpymad output:
![Uploading x.png…]()

madx output:
[Uploading madx.pdf…]()
HIMM_cpymad:
```
TITLE,'HIMM Project';
  OPTION, INFO, -ECHO,WARN;
 BEAM, particle = carbon, energy = 0.007;

! Defining elements

! drift--------------------------------------------------------------

  D11:drift,l=1.75;
  D12:drift,l=0.40;
  D13:drift,l=0.25;
  D14:drift,l=0.10;
  D15:drift,l=0.13;
  D16:drift,l=0.15;
  D17:drift,l=1.775;
  D18:drift,l=0.125;
  D19:drift,l=0.25;
  D1a:drift,l=0.53;

  D21:drift,l=0.43;
  D22:drift,l=0.35;
  D23:drift,l=0.40;
  D24:drift,l=0.15;
  D25:drift,l=2.00;
  D26:drift,l=0.44;
  D27:drift,l=0.10;
  D28:drift,l=0.24;
  D29:drift,l=1.75;

  D31:drift,l=0.67;
  D32:drift,l=0.10;
  D33:drift,l=0.63;
  D34:drift,l=0.40;
  D35:drift,l=0.25;
  D36:drift,l=0.13;
  D37:drift,l=0.15;
  !D38:drift,l=2.00;
  D39:drift,l=0.45;
  D3a:drift,l=0.33;
 D3b:drift,l=0.125;
 D3c:drift,l=1.775;
 
  D41:drift,l=0.43;
  D42:drift,l=0.35;
  D43:drift,l=0.40;
  D44:drift,l=0.15;
  !D45:drift,l=2.00;
  D46:drift,l=0.455;
  D47:drift,l=0.075;
  D48:drift,l=0.25;
  D491:drift,l=0.06;
  D492:drift,l=0.07;
  D4a:drift,l=0.81;
 D4b:drift,l=0.73;
 D4c:drift,l=1.17;
! marker-------------------------------------------------------------

  m1:marker;
  m2:marker;
 
! constant definition of dipoles-------------------------------------

  N=8;
  !bero=6.342738
  !Bm=1.58568
  ro = 4.0; !bero/Bm
  leng := ro*(twopi/N);

  Rr=0.07; !Reference radius of field measurement
  a1=0; !quadrupole component in dipoles
  a2=0.0; !end field
  a3=0.0; !end field
  
! dipole without multipole-------------------------------------------

  RB: SBEND, L=leng,ANGLE=TWOPI/N,K0=1/ro,K1=a1*(1/ro)*(1/Rr),
             E1=PI/8,E2=PI/8,FINT=0.55,FINTX=0.55,HGAP=0.037;
  !EB: RBEND, ANGLE=a2*TWOPI/N;
  !EA: RBEND, ANGLE=a3*TWOPI/N;

! dipole definition--------------------------------------------------

   B11:RB;
   B12:RB;
   B21:RB;
   B22:RB;
   B31:RB;
   B32:RB;
   B41:RB;
   B42:RB;

   HB11: LINE=(B11);
   HB12: LINE=(B12);

   HB21: LINE=(B21);
   HB22: LINE=(B22);

   HB31: LINE=(B31);
   HB32: LINE=(B32);

   HB41: LINE=(B41);
   HB42: LINE=(B42);

! quadrupole without multipole---------------------------------------

  QF: QUADRUPOLE, L=0.2, K1=0.799839688766;
  QD: QUADRUPOLE, L=0.2, K1=-1.00783349327;
  QFF: QUADRUPOLE, L=0.35, K1=1.038161630875;
  !FQ: QUADRUPOLE, L=0.15,K1=0.00;

! quadrupole definition----------------------------------------------

  Q11:QF;
  Q12:QD;
  Q13:QFF;

  Q21:QF;
  Q22:QD;
  Q23:QFF;

  Q31:QF;
  Q32:QD;
  Q33:QFF;

  Q41:QF;
  Q42:QD;
  Q43:QFF;

  !FQ41: FQ;

! chromaticity sextupole definition----------------------------------

  SEXTCH:  sextupole,l=0.15, k2=0.0;
  SEXTCV:  sextupole,l=0.15, k2=0.0;

  SH11: SEXTCH;
  SH31: SEXTCH;
  SV21: SEXTCV;
  SV41: SEXTCV;
  
! resonance sextupole definition-------------------------------------

  SEXTR:  sextupole,l=0.15, k2=0.0;

  SR11: SEXTR;
  SR21: SEXTR;
  SR31: SEXTR;
  SR41: SEXTR;
  S41: SEXTR;

! corrector Kicker---------------------------------------------------

  CYX: KICKER, L=0.1;
  CY: VKICKER, L=0.1;
  CX: HKICKER, L=0.1;
  CX11:CX;
  CX31:CX;
  CX32:CX;
  CX41:CX;
  CX42:CX;
  CY11:CY;
  CY22:CY;
  CY31:CY;
  CY32:CY;
  CY41:CY;
  CY42:CY;
  C21:CYX;

! MONITOR------------------------------------------------------------

  PKUP: MONITOR, L=0.25;

  BPM11: PKUP;
  BPM12: PKUP;

  BPM21: PKUP;

  BPM31: PKUP;
  BPM32: PKUP;
  BPM33: PKUP;

  BPM41: PKUP;
  BPM42: PKUP;

  PU11: LINE=(BPM11);
  PU12: LINE=(BPM12);

  PU21: LINE=(BPM21);

  PU31: LINE=(BPM31);
  PU32: LINE=(BPM32);
  PU33: LINE=(BPM33);

  PU41: LINE=(BPM41);
  PU42: LINE=(BPM42);

! ring definition----------------------------------------------------

  CELL1:Line=(D11,Q11,D12,HB11,D13,PU11,D14,CY11,D15,
              SR11,D16,Q12,D17,CX11,D18,SH11,D16,Q13,
              D12,HB12,D19,PU12,D1a);

  CELL2:Line=(CY22,D21,SV21,D22,HB22,D23,Q23,D24,SR21,
              D25,Q22,D26,C21,D27,PU21,D28,HB21,D23,
              Q21,D29);

  CELL3:Line=(D31,PU31,D32,CX31,D33,Q31,D34,HB31,D35,
              PU32,D32,CY31,D36,SR31,D37,Q32,D3c,CX32,D3b,SH31,
              D37,Q33,D34,HB32,D39,CY32,D3a,PU33);

  CELL4:Line=(D41,SV41,D42,HB42,D43,Q43,D44,SR41,D4b,CX42,D4c,
              Q42,D46,CY42,D47,PU42,D48,HB41,D43,Q41,
              D44,S41,D491,CX41,D492,CY41,D491,PU41,D4a);
  
  himm: Line=(CELL1,CELL2,CELL3,CELL4);

  USE SEQUENCE = himm;
//--------------error definition of dipole-------------
SELECT, FLAG = ERROR, CLEAR;
SELECT, FLAG=ERROR, CLASS=B11;
EFCOMP, ORDER=0, RADIUS=0.1,
DKN = {1E-3,0,0},
DKS = {0,0,0};
 SELECT,FLAG=TWISS,COLUMN=name,s,x,y,mux,betx,muy,bety,dx,dy;
TWISS, SAVE, FILE="HIMM-TWISS-BEF";
plot,  range=#s/#e, haxis=s,vaxis=x,y,colour=100; 
```

**Comment by coldfix** [comment]
Can you describe the problem more precisely? What's the MAD-X file that you compare with, what are the expected values?

**Comment by cpyman** [comment]
I set an error to a dipole, and obtain a closed obit, i.e. x. I can obtain the right plot when I use palin Madx code. However, when I call this code in the cpymad, the output x is always zero. That is to say that cpymad can't calculate the closed orbit correctly. Whether or not cpymad can't treat errors any way.
The Madx file and cpymad code is listed above.

**Comment by coldfix** [comment]
The plain MAD-X code as listed above shows x=y=0 everywhere.

**Comment by cpyman** [comment]
So sorry, Thomas.
I have corrected the Madx file, and you can try it again.

**Comment by coldfix** [comment]
It's still the same MAD-X code.

Please do not edit old posts but rather post additional code as new messages. In the above case the three additional lines for doing the TWISS call would have been enough.
